### PR TITLE
Add MySQL databases for the test and development environments

### PR DESCRIPTION
**Pull request by nanafox**

### CODE REVIEW

**Review by DeborahRise — CHANGES_REQUESTED** [review]
Hey Max, there might be some changes or additions to be made to these codes.
Firstly, thank you for the 'FLUSH PRIVILEGES' addition, i remembered late to add that.

`setup_mysql_dev.sql ; password should be hbnb_dev_pwd`
`setup_mysql_test.sql ; password should be hbnb_test_pwd `
`Let us also correcetly create user on setup_mysql_test.sql `

**Comment by DeborahRise** [comment]
I highlited a few minor additions / corrections we be made here. Would have just made them, but I thought its better practice to highlight them

**Comment by nanafox** [comment]
> I highlited a few minor additions / corrections we be made here. Would have just made them, but I thought its better practice to highlight them

Thanks for highlighting them, I have fixed them in my recent commit. Please review.

**Review by DeborahRise — APPROVED** [review]
Well done Sir Nana Fox! 
Executed excellently

**Pull request merged**
